### ISSUE TITLE
meet ASAN check failed when LOG(WARNING)

### ISSUE THREAD

**Issue by zclllyybb** [google/glog#978]
glog version: 0.4.0
The CXX compiler identification is Clang 16.0.1
Extra cxx flags: -O1

Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "5.4.0-109-generic", arch: "amd64", family: "unix"

code:
```c++
        try {
            callback(client);
        } catch (apache::thrift::transport::TTransportException& e) {
            LOG(WARNING) << "retrying call frontend service after "
                         << config::thrift_client_retry_interval_ms << " ms, address=" << address
                         << ", reason=" << e.what();
            std::this_thread::sleep_for(
                    std::chrono::milliseconds(config::thrift_client_retry_interval_ms));
            status = client.reopen(timeout_ms);
            if (!status.ok()) {
                LOG(WARNING) << "client reopen failed. address=" << address
                             << ", status=" << status;
                return status;
            }
            callback(client);
        }
```
when the control flow hit the line 4 `LOG(WARNING)`, we meet an ASAN check failed. stacktrace is like:
```
AddressSanitizer: CHECK failed: asan_thread.cpp:368 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0) (tid=9805)
#0 0x556f5ad77941 in __asan::CheckUnwind() crtstuff.c
#1 0x556f5ad8f412 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) crtstuff.c
#2 0x556f5ad7b663 in __asan::AsanThread::GetStackFrameAccessByAddr(unsigned long, __asan::AsanThread::StackFrameAccess*) crtstuff.c
#3 0x556f5acdfd87 in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) crtstuff.c
#4 0x556f5ace1a73 in __asan::ErrorGeneric::ErrorGeneric(unsigned int, unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long) crtstuff.c
#5 0x556f5ad7550e in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) crtstuff.c
#6 0x556f5acf5405 in localtime_r (/mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be+0x12549405) (BuildId: 93a37407c156289e)
#7 0x556f86ed833a in google::LogMessageTime::LogMessageTime(long, double) gflags_completions.cc
#8 0x556f86ed34ac in google::LogMessage::Init(char const*, int, int, void (google::LogMessage::*)()) gflags_completions.cc
#9 0x556f5d84c466 in doris::Status doris::ThriftRpcHelper::rpc<doris::FrontendServiceClient>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::function<void (doris::ClientConnection<doris::FrontendServiceClient>&)>, int) /root/doris/be/src/util/thrift_rpc_helper.cpp:76:13
......
```

the more code context could be found at https://github.com/apache/doris/blob/faaf0ecc851beb5847e7ec6dabfcab4f8090117c/be/src/util/thrift_rpc_helper.cpp#L76C1-L76C1

Could you confirm it is a glog bug or not?

**Comment by sergiud** [comment]
> glog version: 0.4.0

This version of glog is over 4 years old and is no longer supported. Please use the latest release or better yet the version at head.

**Comment by zclllyybb** [comment]
> > glog version: 0.4.0
> 
> This version of glog is over 4 years old and is no longer supported. Please use the latest release or better yet the version at head.

ok. I will upgrade it and test then today.

**Comment by zclllyybb** [comment]
> > glog version: 0.4.0
> 
> This version of glog is over 4 years old and is no longer supported. Please use the latest release or better yet the version at head.

sorry, I thought we are using 0.4.0 by mistake. I checked it again, the correct version is 0.6.0, seems the newest release version. could you please think check this problem again? or what other infomation do I need to provide?

**Comment by sergiud** [comment]
Please test the version at head since it contains a [related issue fix](https://github.com/google/glog/pull/954) and report back.

**Comment by zclllyybb** [comment]
> Please test the version at head since it contains a [related issue fix](https://github.com/google/glog/pull/954) and report back.

well, it doesn't work. the problem still occur. Is there any extra information will be useful for troubleshooting this?

**Comment by sergiud** [comment]
Yes, we need a minimal reproducer to confirm the problem actually occurs in glog directly and is not caused by any of your dependencies. I do not believe anyone will be looking into debugging third party projects.

**Comment by sergiud** [comment]
I'll close the issue since the sanitizer failure occurs in `localtime_r` which is part of the C library. The issue is therefore not directly related to glog.
